version: "3.8"

services:
  express_rest_api:
    container_name: my_express_rest_api
    build: ./app/
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql_db
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
    networks:
      - database_net
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1G
  mysql_db:
    container_name: my_mysql_db
    image: mysql:latest
    # Important command to allow legacy authentications for old versions
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_volume:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - database_net
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  mysql_db_volume:
    name: "mysql_db_volume"

networks:
  database_net:
    driver: bridge
    name: database_net
